version: '3.7'
services:
  api:
    image: sammiio/invoices-api
    build: ./api
    entrypoint: [ npx ]
    command:
    - nodemon
    - index.js
    environment:
      PORT: '3000'
      NATS_HOST: nats
      REDIS_HOST: redis
    ports:
    - '3000:3000'
    volumes:
    # use a bind-mount to get src
    # into the container
    - ./api:/app
    # create a data volume so
    # we can get node_modules into our
    # bind-mounted container
    - /app/node_modules
    depends_on:
    - nats
    - redis
  worker:
    image: sammiio/invoices-worker
    build:
      context: ./worker
      target: dev
    entrypoint: [ godev ]
    environment:
      NATS_HOST: nats
    volumes:
    - ./worker:/app
    depends_on:
    - nats
  nats:
    image: nats:2.0.4-linux
    ports:
    - '8222'
  redis:
    image: redis:5.0.5-alpine
