version: '3.7'
services:
  api:
    image: sammiio/invoices-api
    build: ./api
    entrypoint: [ npx ]
    command:
    - nodemon
    - index.js
    environment:
      PORT: '3000'
    ports:
    - '3000:3000'
    volumes:
    # use a bind-mount to get src
    # into the container
    - ./api:/app
    # create a data volume so
    # we can get node_modules into our
    # bind-mounted container
    - /app/node_modules
  worker:
    image: sammiio/invoices-worker
    build: ./worker
    # volumes:
    # - ./worker:/app
    depends_on:
    - nats
  nats:
    image: nats:latest
    ports:
    - '8222'
